- hosts: all
  remote_user: ec2-user
  become: true
  tasks:
     - name: installing apache
       yum:
         name: httpd
         state: present

     - name: starting apache
       service:
         name: httpd
         state: started

     - name: copying index.html
       copy: 
          src: index.html
          dest: /var/www/html
